name: "units-test"
on:
  push:

jobs:
  # unit tests
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: NODE_OPTIONS=--openssl-legacy-provider npm ci
    - run: npm test
